### ISSUE TITLE
Remove any login password prompts

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/seqr#71]
seqr fundamentally supports both password-based and OAuth2-based authentication. For our deployment, we've disabled password-based log-ins and rely on Google OAuth2 flows instead. However, there are still a few remaining occurrences where log-in pages show password prompts, which is confusing for users: they won't be able to log in that way and we wouldn't want them to accidentally enter their Google account password.

Some of this might be easy to fix by redirecting https://seqr.populationgenomics.org.au/login directly to https://seqr.populationgenomics.org.au/login/google-oauth2.

In particular, the following flows still show a password prompt:
- Unauthorized request, e.g. try to load https://seqr.populationgenomics.org.au/project/R0001_na12878_trio/project_page if not previously logged in. This will redirect to https://seqr.populationgenomics.org.au/login?next=/project/R0001_na12878_trio/project_page. Instead, it should redirect to https://seqr.populationgenomics.org.au/login/google-oauth2.
- Logging out redirects to https://seqr.populationgenomics.org.au/login, but should redirect to https://seqr.populationgenomics.org.au/.

One added complication is that we'd still want to allow local development, for which the OAuth2 flow currently doesn't work.

**Comment by danielreti** [comment]
After lots of exploration, I cannot seem to replicate these issues. 
https://seqr.populationgenomics.org.au/login returns an (internal) 404 page. I have not yet found a way to navigate to it without explicitly typing the url. 
Unauthorised requests like the one in the example link correctly to google-oauth2 and not /login. 
Logging out seems to redirect correctly to https://seqr.populationgenomics.org.au/ rather than /login, however this doesn't seem to be a true logout as clicking sign in does not prompt for credentials again (presumably there is some delay before credentials are needed again). 
For local development, OAuth2 does not currently work and instead logging in via /login does work as intended. 
Please advise @lgruen

**Comment by lgruen** [comment]
Hmm, these were definitely issues before the recent merges. But I can't reproduce this myself anymore either, so it seems to have gotten resolved already upstream. Nice! :)

Thanks a lot for trying to reproduce this!
